// Copyright 2024 Tommaso Visconti (@tommyblue)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

/* Handedness. */
#define MASTER_RIGHT

/* Reset. */
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED GP17
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 1000U

/* SPI & PMW3360 settings. */
#define SPI_DRIVER SPID0
#define SPI_SCK_PIN GP23
#define SPI_MISO_PIN GP21
#define SPI_MOSI_PIN GP20
#define POINTING_DEVICE_CS_PIN GP22
// #define SPLIT_POINTING_ENABLE
// #define POINTING_DEVICE_RIGHT
#define POINTING_DEVICE_DEBUG

#define MATRIX_ROWS 8
#define MATRIX_COLS 6
#define MATRIX_COL_PINS { GP2, GP3, GP4, GP5, GP6, GP7 }
#define MATRIX_ROW_PINS { GP8, GP9, GP12, GP13 }
#define MATRIX_COL_PINS_RIGHT { GP2, GP3, GP4, GP5, GP6, GP7 }
#define MATRIX_ROW_PINS_RIGHT { GP8, GP9, GP12, GP13 }
